config/routes.rb
Rails.application.routes.draw do
  resources :packages

  resources :carts

  resources :cart_items

  resources :perks

  resources :user_game_ids

  resources :game_instances

  resources :games do
    member do
      get '/get_game_instances' => 'games#get_game_instances'
    end
  end

  resources :comments

  resources :groupings do
    post :update_grouping_order, on: :collection
  end

  resources :topics

  resources :forums do
    member do
      get '/new' => 'forums#new'
    end
    post :update_row_order, on: :collection
  end

  resources :admin_roles

  resources :users do
    member do
      get '/new_password' => 'users#new_password' , as: 'update_password'
      post 'image_upload' => 'users#image_upload'
    end
  end

  get '/username_avaliable' => 'users#username_avaliable'

  post 'cart/:id/delivered' => 'carts#delivered'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'

  root 'static_pages#index'

  post 'checkout' => 'static_pages#checkout'

  post 'add_to_cart' => 'carts#add_to_cart'
  delete 'remove_from_cart' => 'carts#remove_from_cart'
  get 'admin_panel' => 'static_pages#admin_panel'

  if Rails.env.development?
    get 'cert' => 'static_pages#cert'
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:checkout]
  

	def index
		# @client_token = Braintree::ClientToken.generate
		@main_topics = Topic.where(forum_id: Forum.where(main_feed: true).pluck(:id)).order(:created_at).order(:sticky)
	end

	def cert
		send_file "#{Rails.root}/tmp/certificates/ssl.crt"
	end

	def create
		redirect_to root_path
	end

	def checkout
	  nonce = params[:payment_method_nonce]
	  render action: :new and return unless nonce
	  result = Braintree::Transaction.sale(
	    amount: "10.00",
	    payment_method_nonce: nonce
	  )

	  flash[:notice] = "Sale successful. Head to Sizzler" if result.success?
	  flash[:alert] = "Something is amiss. #{result.transaction.processor_response_text}" unless result.success?
	  redirect_to action: :new
	end

	def admin_panel
		@games = Game.all.order(:title)
		@game_instances = GameInstance.all.order(:title)
	end

end

app/views/static_pages/admin_panel.html.haml
= link_to 'Create New Game', new_game_path
%br
= link_to 'Create New Game Instance', new_game_instance_path
%br
= link_to 'Create New Perk', new_perk_path
%br
= link_to 'Create New Package', new_package_path
%br
= link_to 'Users List', users_path
%br
= link_to 'Carts', carts_path
%br

app/views/static_pages/index.html.haml
%h1.text-center Main List
=flash_msg
- @main_topics.each do |topic|
  %table.table{class: "#{topic.class.to_s.downcase}-part"}
    %tr.warning
      %td.remove-border
        %h4
          - if topic.class.to_s.downcase == 'topic' && topic.sticky
            = g_pushpin
          - if topic.class.to_s.downcase == 'forum' && topic.admins_only
            = g_cert
          - if topic.locked
            = g_lock
          - if topic.deleted
            = g_eye
          = link_to topic.title, topic
          %br
          %p.text-inline.inline
            %small
              Created by #{link_to topic.creator.username, user_path(topic.creator)} about #{local_time_ago(topic.created_at)}
          %p.inline.pull-right
            %small
              -if topic.last_updated
                most recent post: #{topic.last_updated}
    %tr.warning
      %td
        =topic.body
  %br