config/routes.rb
Rails.application.routes.draw do
  resources :packages

  resources :carts

  resources :cart_items

  resources :perks

  resources :user_game_ids

  resources :game_instances

  resources :games do
    member do
      get '/get_game_instances' => 'games#get_game_instances'
    end
  end

  resources :comments

  resources :groupings do
    post :update_grouping_order, on: :collection
  end

  resources :topics

  resources :forums do
    member do
      get '/new' => 'forums#new'
    end
    post :update_row_order, on: :collection
  end

  resources :admin_roles

  resources :users do
    member do
      get '/new_password' => 'users#new_password' , as: 'update_password'
      post 'image_upload' => 'users#image_upload'
    end
  end

  get '/username_avaliable' => 'users#username_avaliable'

  post 'cart/:id/delivered' => 'carts#delivered'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'

  root 'static_pages#index'

  post 'checkout' => 'static_pages#checkout'

  post 'add_to_cart' => 'carts#add_to_cart'
  delete 'remove_from_cart' => 'carts#remove_from_cart'
  get 'admin_panel' => 'static_pages#admin_panel'

  if Rails.env.development?
    get 'cert' => 'static_pages#cert'
  end

end

app/models/grouping.rb
class Grouping < ActiveRecord::Base
	validates_presence_of :title
	validates_uniqueness_of :title, scope: :forum_id
	scope :find_by_item_ids, ->(id) { where(:id => id).order('title DESC') }
	belongs_to :forum, :class_name => 'Forum', :foreign_key => 'forum_id'
	has_many :forums, :class_name => 'Forum', :foreign_key => 'grouping_id'

	include RankedModel
  ranks :row_order, :with_same => :forum_id 

	def self.find_or_create_by_title(title)
		if grouping = Grouping.where(title: title).first
			return grouping.first
		else
			title = 'nil' unless title.present?
			return Grouping.create(title: title)
		end
	end

	def self.top_level_groups
		return Grouping.rank(:row_order).where(forum_id: nil)
	end	

	def id
		if super == 0
			return 'nil'
		else
			return super
		end
	end
end

app/controllers/groupings_controller.rb
class GroupingsController < ApplicationController
  before_action :set_grouping, only: [:show, :edit, :update, :destroy]

  def update_grouping_order
    if grouping = Grouping.find_by_id(params[:grouping][:id])
      mover = 0
      case params[:grouping][:direction]
        when 'up'
          mover = -1
        when 'down'
          mover = 1
      end
      grouping.row_order_position = params[:grouping][:position].to_i + mover
      if grouping.save
        render :json=>true and return
      end
    end
    render :json=>false and return
  end

  # GET /groupings/1/edit
  def edit
  end

  # POST /groupings
  # POST /groupings.json
  def create
    @grouping = Grouping.new(grouping_params)
    if @grouping.save
      if params["ajax"]
        @games = [[ '', -2 ]] + Game.all.pluck(:name, :id)
        @game_instances = []
        render partial: 'forums/forums_grouping', locals: { forum_group_id: @grouping.id, forum_group: @grouping, this_forum: @grouping.forum, forums: @grouping.forum.get_groups_and_grouped_forums[1], position: Grouping.all.count } and return
      else
        redirect_to @grouping, notice: 'Grouping was successfully created.'
      end
    else
      if params["ajax"]
        render nothing: true;
      else
        render :new
      end
    end
  end

  # PATCH/PUT /groupings/1
  # PATCH/PUT /groupings/1.json
  def update
    respond_to do |format|
      if @grouping.update(grouping_params)
        format.html { redirect_to @grouping, notice: 'Grouping was successfully updated.' }
        format.json { render :show, status: :ok, location: @grouping }
      else
        format.html { render :edit }
        format.json { render json: @grouping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groupings/1
  # DELETE /groupings/1.json
  def destroy
    count = @grouping.forum.children.where(grouping_id: nil).count
    @grouping.forums.each do |forum|
      forum.grouping_id = nil;
      forum.row_order_position = count
      forum.save
    end
    @grouping.destroy
    if params["ajax"]
      render nothing: true
    else
      redirect_to groupings_url, notice: 'Grouping was successfully destroyed.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grouping
      @grouping = Grouping.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grouping_params
      params.require(:grouping).permit(:title, :forum_id)
    end
end

app/helpers/groupings_helper.rb
module GroupingsHelper
end

app/views/groupings/_form.html.haml
= form_tag('/',class: "form-horizontal") do |f|
  .form-group
    = label_tag 'new-group-title', 'Title', class: 'col-sm-1 control-label' 
    .col-sm-6
      = text_field_tag 'new-group-title','', class: 'form-control' 
    .col-sm-2
      %button.btn.btn-default.btn-xs#create-new-group.form-control{"aria-expanded" => "false", :type => "button", data: { forum_id: forum_id }}
        Create Group

app/views/groupings/edit.html.haml
%h1 Editing Grouping
= render 'form'
= link_to 'Show', @grouping
|
\#{link_to 'Back', groupings_path}

app/views/groupings/index.html.haml
%p#notice= notice
%h1 Listing Groupings
%table
  %thead
    %tr
      %th Title
      %th{:colspan => "3"}
  %tbody
    - @groupings.each do |grouping|
      %tr
        %td= grouping.title
        %td= link_to 'Show', grouping
        %td= link_to 'Edit', edit_grouping_path(grouping)
        %td= link_to 'Destroy', grouping, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Grouping', new_grouping_path

app/views/groupings/new.html.haml
%h1 New Grouping
= render 'form'
= link_to 'Back', groupings_path

app/views/groupings/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @grouping.title
= link_to 'Edit', edit_grouping_path(@grouping)
|
\#{link_to 'Back', groupings_path}