config/routes.rb
Rails.application.routes.draw do
  resources :packages

  resources :carts

  resources :cart_items

  resources :perks

  resources :user_game_ids

  resources :game_instances

  resources :games do
    member do
      get '/get_game_instances' => 'games#get_game_instances'
    end
  end

  resources :comments

  resources :groupings do
    post :update_grouping_order, on: :collection
  end

  resources :topics

  resources :forums do
    member do
      get '/new' => 'forums#new'
    end
    post :update_row_order, on: :collection
  end

  resources :admin_roles

  resources :users do
    member do
      get '/new_password' => 'users#new_password' , as: 'update_password'
      post 'image_upload' => 'users#image_upload'
    end
  end

  get '/username_avaliable' => 'users#username_avaliable'

  post 'cart/:id/delivered' => 'carts#delivered'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'

  root 'static_pages#index'

  post 'checkout' => 'static_pages#checkout'

  post 'add_to_cart' => 'carts#add_to_cart'
  delete 'remove_from_cart' => 'carts#remove_from_cart'
  get 'admin_panel' => 'static_pages#admin_panel'

  if Rails.env.development?
    get 'cert' => 'static_pages#cert'
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :forum
	belongs_to :creator, :class_name => 'User', :foreign_key => 'created_by'
	belongs_to :destroyer, :class_name => 'User', :foreign_key => 'deleted_by'
	belongs_to :parent, :class_name => 'Forum', :foreign_key => 'forum_id'
	has_many :comments, dependent: :destroy

	after_save :update_self_and_parent

	def update_self_and_parent
		self.update_column(:last_updated, Time.now.utc)
		if self.parent
			self.parent.update_attribute(:last_updated, Time.now.utc)
		end
	end

	def parent_chain
		return self.parent.parent_chain << self
	end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    my_breadcrumbs(@topic)
    @new_topic = Topic.new
    @new_comment = Comment.new
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params) if topic_params

    @topic.created_by = current_user.id

    if @topic.save
      if params["topic"] && params["ajax"]
        render partial: 'topics/topic_table', locals: {topics: @topic.parent.topics} and return
      else  
        my_breadcrumbs(@topic)
        @new_topic = Topic.new
        @new_comment = Comment.new
        redirect_to @topic, notice: 'Topic was successfully created.'
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    if params["what"]
      topic = Topic.find_by_id(params["id"])
      case params["what"]
        when 'lock'
          topic.update_attribute(:locked, true)
        when 'un_lock'
          topic.update_attribute(:locked, false)
        when 'stick'
          topic.update_attribute(:sticky, true)
        when 'un_stick'
          topic.update_attribute(:sticky, false)
        when 'delete'
          topic.update_attributes(:deleted => true, :deleted_by => current_user.id)
        when 'un_delete'
          topic.update_attributes(:deleted => false)
        when 'destroy'
          topic.destroy
          topic = nil
        end
      render partial: 'layouts/tf_row', locals: { obj: topic, admin: true } and return unless params["what"] == 'stick' || params["what"] == 'un_stick'
      render partial: 'topics/topic_table', locals: {topics: topic.parent.topics} and return
    else
      respond_to do |format|
        if @topic.update(topic_params)
          format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
          format.json { render :show, status: :ok, location: @topic }
        else
          format.html { render :edit }
          format.json { render json: @topic.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :created_by, :sticky, :body, :locked, :deleted, :deleted_by, :last_updated, :forum_id)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.haml
= form_for(new_topic, html: { class: "form-horizontal" }) do |f|
  - if new_topic.errors.any?
    #error_explanation
      %h2
        = pluralize(new_topic.errors.count, "error")
        prohibited this new_topic from being saved:
      %ul
        - new_topic.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :title, class: 'col-sm-1 control-label'
    .col-sm-7
      = f.text_field :title, class: 'form-control ' 
    = f.label :locked, class: 'col-sm-1 control-label'
    .col-sm-1
      = f.check_box :locked, class: 'form-control'
    = f.label :sticky, class: 'col-sm-1 control-label'
    .col-sm-1
      = f.check_box :sticky, class: 'form-control'
  .form-group
    = f.label :body, class: 'col-sm-1 control-label'
    .col-sm-9
      = f.text_area :body, class: 'form-control'
    .col-sm-2
      %button.btn.btn-default#create-new-topic{"aria-expanded" => "false", :type => "button"}
        Create Topic

app/views/topics/_topic_options.html.haml
%tr.topic-options{ style: 'display:none', id: "topic-#{obj.id}" }
  %td
  - if obj.deleted
    %td
      Deleted: #{obj.deleted}
    %td
      Deleted by: #{obj.destroyer}
    %td
      = link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'
    %td
      -if obj.locked
        = link_to 'UnLock', '#', class: 'btn btn-primary btn-xs'
      -else
        = link_to 'Lock', '#', class: 'btn btn-primary btn-xs'
  - else
    %td
      Deleted: #{obj.deleted}
    %td
      = link_to 'Delete', '#', class: 'btn btn-default btn-xs'
    %td
      = link_to 'Destroy', '#', class: 'btn btn-danger btn-xs'
    %td
      -if obj.locked
        = link_to 'Unlock', '#', class: 'btn btn-primary btn-xs'
      -else
        = link_to 'Lock', '#', class: 'btn btn-primary btn-xs'

app/views/topics/_topic_table.html.haml
%tbody
  - topics.each do |topic|
    %tr{ id: "topic-#{topic.id}-update-section" }
      = render partial: 'layouts/tf_row', locals: { obj: topic }

app/views/topics/_topics.html.haml
- if current_user && current_user.super_admin?
  %button.btn.btn-xs.btn-default.new-topic-toggle{"aria-expanded" => "false", :type => "button"}
    New Topic
#new-topic-forum{hidden: true}
  = render partial: "topics/form", locals: { new_topic: new_obj }
%table.table#topic-table
  %tbody
    - topics.each do |topic|
      %tr{ id: "topic-#{topic.id}-update-section" }
        = render partial: 'layouts/tf_row', locals: { obj: topic }

app/views/topics/edit.html.haml
%h1 Editing Topic
= render 'form'
= link_to 'Show', @topic
|
\#{link_to 'Back', topics_path}

app/views/topics/new.html.haml
%h1 New Topic
= render 'form'
= link_to 'Back', topics_path

app/views/topics/show.html.haml
%h1.text-center #{@topic.title}
=flash_msg
=render_breadcrumbs
.bg-warning
  %p
    Created by #{link_to @topic.creator.username, user_path(@topic.creator.id)} on #{local_time(@topic.created_at)}
  %p.lg-font
    = @topic.body

= render partial: 'comments/comments', locals: { comments: @topic.comments, new_comment: @new_comment, topic_id: @topic.id}