config/routes.rb
Rails.application.routes.draw do
  resources :packages

  resources :carts

  resources :cart_items

  resources :perks

  resources :user_game_ids

  resources :game_instances

  resources :games do
    member do
      get '/get_game_instances' => 'games#get_game_instances'
    end
  end

  resources :comments

  resources :groupings do
    post :update_grouping_order, on: :collection
  end

  resources :topics

  resources :forums do
    member do
      get '/new' => 'forums#new'
    end
    post :update_row_order, on: :collection
  end

  resources :admin_roles

  resources :users do
    member do
      get '/new_password' => 'users#new_password' , as: 'update_password'
      post 'image_upload' => 'users#image_upload'
    end
  end

  get '/username_avaliable' => 'users#username_avaliable'

  post 'cart/:id/delivered' => 'carts#delivered'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'

  root 'static_pages#index'

  post 'checkout' => 'static_pages#checkout'

  post 'add_to_cart' => 'carts#add_to_cart'
  delete 'remove_from_cart' => 'carts#remove_from_cart'
  get 'admin_panel' => 'static_pages#admin_panel'

  if Rails.env.development?
    get 'cert' => 'static_pages#cert'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :email
  validates_uniqueness_of :email, :username
  validates :password,length: { minimum: 6 }, :allow_blank => true
  validates :admin_obj_id, :presence => true, :if => :admin_level_present?
  before_save :create_username
  has_many :admin_roles, dependent: :destroy
  has_many :forums, :class_name => "Forum", :foreign_key => 'created_by' 
  # belongs_to :user, class_name: 'User', foreign_key: :banned_by

  attr_accessor :admin_level, :admin_obj_id
  # crop_attached_file :image

  has_secure_password

  def to_json
    self.to_json(only: [ :id, :username ])
  end

  def create_username
  	self.username = Faker::Internet.user_name unless self.username
  end

  def admin_level_present?
    return true if self.admin_level && self.admin_level == "Forum"
    return false
  end

  def admin?
  	return true if self.admin_roles.count > 0
  	return false
  end

  def super_admin?
  	return true if king? || queen?
  	return false
  end

  def king?
  	return true if self.admin_roles.map{|m| m.admin_type.downcase}.include?('king')
  	return false
  end

  def queen?
  	return true if self.admin_roles.map{|m| m.admin_type.downcase}.include?('queen')
  	return false
  end

  def forum_admin_ids
    ['']
  end

  def highest_admin_level
    return admin_types_array.first
  end

  def banned_by
  	User.find_by_id(super)
  end

  def admin_of?(obj)
    return true if super_admin?
    return false if obj.id == nil
    roles = AdminRole.where(admin_id: obj.id).where(admin_type: obj.class.to_s.downcase)
    return true if roles.count > 0
    return false
  end

  def admin_types
    return self.admin_roles.map{ |m| [m.admin_type.capitalize,m.admin_id].reject!(&:blank?).join(':')}.join(',')
  end

  def admin_types_array
    return self.admin_roles.map{ |m| [m.admin_type.capitalize,m.admin_id].reject!(&:blank?).join(':')}
  end

  def higher_than?(other)
    return true if self.king?
    return true if !other.king?  && !other.queen? && self.queen?
    return true if !other.queen? && self.admin_types.lenght > 0
    return false
  end

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end
    
  def reprocess_avatar
    image.reprocess!
  end
  
  def avatar_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(image.path(style))
  end

  def destroy_original
    File.unlink(self.image.path)
  end

  def cart
    return @cart if @cart
    cart = Cart.where(user_id: self.id)
    if cart.count > 0
      cart = cart.where(donation_id: nil)
      if cart.count > 0
        return @cart = cart.first
      end
    end
    return @cart = Cart.create(user_id: self.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :new_password]
  before_action :authenticated_king, only: :destroy
  before_action :authenticated_super_admin, except: [:destroy, :show, :edit, :new_password, :create, :update, :new, :username_avaliable]
  # before_action :authorize_admin, only: [:index]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def username_avaliable
    render json: User.find_by_username(params["username"]) ? false : true
  end

  # GET /users/new
  def new
    if (current_user)
      redirect_to user_path(current_user.id) and return
    end
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @forum_dropdown = Forum.all.pluck(:title, :id) || []
  end

  def new_password

  end

  def promote

  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    # if params["commit"] == 'Crop'
    #   if @user.update(user_params)
    #     # @user.reprocess_avatar
    #     # @user.destroy_original
    #   end
    #   redirect_to user_path(@user.id) and return
    # end
    if params["user"]["current_password"]
      unless @user.authenticate(params["user"]["current_password"])
        redirect_to update_password_user_path(@user), :flash => { :error => "Current password is incorrect!" }
        return
      end
      notice = "Password was updated successfully"
    else
      notice = 'User was successfully updated.'
    end
    if @user.update(user_params)
      ar = {}
      ar["user_id"] = @user.id
      ar["admin_type"] = params["user"]["admin_level"] if params["user"]["admin_level"].present?
      ar["admin_id"] = params["user"]["admin_obj_id"] if params["user"]["admin_obj_id"].present?

      AdminRole.create(ar) if ar.keys.count > 1
      session[:user_id] = @user.id if current_user == @user
      
      # render 'cropper' and return 
      redirect_to user_path(@user.id) and return

      # format.html { redirect_to @user, notice: notice }
      # format.json { render :show, status: :ok, location: @user }
    else
      @forum_dropdown = Forum.all.pluck(:title, :id) || []
      render :edit
      # format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation,:email, :email_verified, :phone_number, :phone_provider, :about_me, :banned, :permma_banned, :banned_by, :customer_id, :image, :crop_x, :crop_y, :crop_w, :crop_h, :admin_level, :admin_obj_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.haml
=flash_msg
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  - if current_user.super_admin?
    .form-group
      = f.label 'Banned'
      = f.check_box :banned,{checked: @user.banned},true,false
    - if current_user.king?
      .form-group
        = f.label 'Permma Banned'
        = f.check_box :permma_banned,{checked: @user.permma_banned},true,false
      - if @user.super_admin?
        .form-group
          = f.label t('user.phone_number')
          = f.text_field :phone_number, class: 'form-control'
        .form-group
          = f.label t('user.phone_provider')
          = f.text_field :phone_provider, class: 'form-control'
      .form-group
        = label :admin_level_label, 'Promote'
        = select_tag "user[admin_level]", options_for_select([@user.highest_admin_level] + AdminRole.restricted_admins(current_user)), class: 'form-control admin-user-level'
      .form-group.admin-obj-id{ hidden: "#{@user.errors.any? ? false : true }"}
        = label :admin_obj_id_label, 'Admin Of:'
        = select_tag "user[admin_obj_id]", options_for_select([@user.forum_admin_ids.first] + @forum_dropdown), class: 'form-control'

  .form-group
    = f.label t('user.username')
    %small
    = f.text_field :username, class: 'form-control'
  .form-group
    = f.label t('user.email')
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label t('user.about_me')
    %small
      =t('user.about_me_description')
    = f.text_area :about_me, class: 'form-control about-me-text-area'
  .actions
    = f.submit t('submit'), class: 'btn btn-primary btn-lg'

app/views/users/_sign_up_form.html.haml
=flash_msg
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  .form-group#username-textfield
    = f.label 'User Name'
    %small#username-notice
      &nbsp;
    %br
      = f.text_field :username, class: 'form-control', id: 'username-creation'
  .form-group
    = f.label t('user.email')
    %br
      = f.text_field :email, class: 'form-control'
  .form-group
    = f.label t('user.password')
    %br
      = f.password_field :password, class: 'form-control'
  .form-group
    = f.label t('user.password_confirmation')
    %br
      = f.password_field :password_confirmation, class: 'form-control'
  .form-group
    = f.submit t('submit'), class: 'btn btn-primary btn-lg'

app/views/users/_update_password.html.haml
=flash_msg
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label t('user.current_password')
    %br
      = f.password_field :current_password, class: 'form-control'
  .form-group
    = f.label t('user.password')
    %br
      = f.password_field :password, class: 'form-control'
  .form-group
    = f.label t('user.password_confirmation')
    %br
      = f.password_field :password_confirmation, class: 'form-control'
  .actions
    = f.submit t('submit'), class: 'btn btn-primary btn-lg'

app/views/users/edit.html.haml
%h1
	=@user.username
= render 'edit_form'
= link_to t('show'), @user, class: 'btn btn-default btn-xs'
=link_to t('back'), users_path, class: 'btn btn-default btn-xs'

app/views/users/index.html.haml
%h1.text-center
  =t('listing_users')
=flash_msg
%table.table.table-striped.table-bordered
  %thead
    %tr
      %th.text-center
        =t('user.username')
      %th.text-center
        =t('user.email')
      %th.text-center
        =t('user.allowed')
      %th.text-center
        Admin level
      %th{:colspan => "3"}
  %tbody
    - @users.each do |user|
      %tr
        %td
          - if current_user == user
            %span.glyphicon.glyphicon-star{"aria-hidden" => "true"}
          = user.username
        %td= user.email
        %td.text-center
          - if user.banned
            %span.glyphicon.glyphicon-remove-sign.red.md-glyphicon{"aria-hidden" => "true"}
          - else
            %span.glyphicon.glyphicon-ok-sign.green.md-glyphicon{"aria-hidden" => "true"}  
        %td.text-center
          = user.admin_types
        %td.text-center= link_to t('details'), user, class: 'btn btn-primary btn-xs'
        %td.text-center= link_to t('edit'), edit_user_path(user), class: 'btn btn-default btn-xs'
        %td.text-center= link_to t('destroy'), user, method: :delete, data: { confirm: t('are_you_sure') }, class: 'btn btn-danger btn-xs'
%br

app/views/users/login.html.haml
=flash_msg
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label t('user.email')
    %br
      = f.text_field :email, class: 'form-control'
  .form-group
    = f.label t('user.password')
    %br
      = f.text_field :password_digest, class: 'form-control'
  .form-group
    = f.label t('user.password_confirmation')
    %br
      = f.text_field :password_digest, class: 'form-control'
  .form-group
    = f.submit t('submit'), class: 'btn btn-primary btn-lg'

app/views/users/new.html.haml
%h1 New User
=flash_msg
= render 'sign_up_form'
= link_to t('back'), users_path

app/views/users/new_password.html.haml
=render partial: 'update_password'
= link_to 'Back', @user, class: 'btn btn-default btn-xs'

app/views/users/show.html.haml
=flash_msg
%p
  %strong UserName:
  = @user.username
- if current_user == @user || current_user && current_user.king?
  %p
    %strong Email:
    = @user.email
  %p
    %strong Email verified:
    = @user.email_verified
%p
  %strong About me:
  = @user.about_me
%p
  %strong Admin Type:
  = @user.admin_types
- if current_user && current_user.super_admin?
  %p
    %strong Banned:
    = @user.banned
  - if @user.banned
    %p
      %strong Banned by:
      = link_to "#{@user.banned_by.username} / #{@user.banned_by.email}", user_path(@user.banned_by)

- if current_user && (current_user.super_admin? || (current_user.id.to_s == params["id"]))
  = link_to t('edit'), edit_user_path(@user), class: 'btn btn-default btn-xs'
  = link_to 'Add gamer id', new_user_game_id_path, class: 'btn btn-default btn-xs'
  - if (current_user.id.to_s == params["id"])
    = link_to t('user.change_password'), update_password_user_path(@user), class: 'btn btn-default btn-xs'